# Lang
language: en

# Dark Mode
dark: false 

# Header
menu:
  Home: /
  Archives: /archives
  # About: /about
rss: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: Zhige Xin 
# description: I am a researcher, software engineer and open-source enthusiast. Now I focus on social network and machine learning. This is my [resume](/resume_zhige_xin.pdf).
links:
  # About: /about/index.md
  Blog: /archives
  GitHub: https://github.com/xinzhige
  Linkedin: https://linkedin.com/in/isaiah-zhige-xin/
  Facebook: http://facebook.com/isaiah.xin/
  # Twitter : http://twitter.com/


# Info
archive_footer_content: Archive
post_footer_content: Post
